<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<link type="text/css" rel="stylesheet" href="css/main-style.css">
		<link type="text/css" rel="stylesheet" href="css/iskolatortenet-style.css" >
		<link type="text/css" rel="stylesheet" href="css/slide-style.css">
		<title>Szilágyi Erzsébet Gimnázium</title>
	
	</head>
	
	<body>
		<?php include("page-header.php") ?>
		
				
		<div class="content-container">
			<div class="content-title">Iskolatörténet</div>
			<div class="name">
				<p><h3>NÉVADÓNK: SZILÁGYI ERZSÉBET</h3></p>
Szilágyi Erzsébet Hunyadi János felesége, Hunyadi László és Hunyadi Mátyás anyja, Szilágyi Mihály testvérhúga, meghalt - Kaprinay szerint - 1484 körül, Salamon szerint pedig valószínű, hogy már 1483. április 25-én nem volt az élők sorában.	
			</div>
			<div class="name-history">
				<p>ÉLETE</p>
Történelmi szerepe azzal a jelenettel kezdődik, amikor megesketteti V.László királyt, hogy fiainak nem lesz bántódásuk Cillei Ulrik meggyilkol- tatása miatt. Ismeretes, hogy a király ezen esküjét, mint tőle erőszakkal kicsikartat, amint a Hunyadi-ház ellenségei közé juthatott, azonnal megszegte, Hunyadi Lászlót lefejeztette, Mátyást foglyul ejtette. Ekkor tűnt ki, mennyire egyezik Szilágyi Erzsébet vére és cselekvésmódja a Szilágyi Mihályéval. Valódi renaissance amazon, akit kortársai méltán neveztek Ťhős asszonynakť (mulier heroica). Családja veszedelmén nem asszonysírással, hanem pénzzel és fegyveres erővel igyekezett segíteni. A király már 1457-ben annyira megrettent e nőtől, hogy mindenáron egyezkedni akart vele, de a két ízben megismételt kísérlet nem ment dűlőre s a király még azon év novemberében meghalván, Erzsébet asszony minden erejét megfeszítette, hogy fiát a trónra emelhesse. A Hunyadi-ház hatalmas vagyonának birtokában, pazarul szórta a pénzt a választás előkészítésére. Ulisis, a milánói fejedelem követe a császári udvar tudtára adja e célra tett költekezéseit, amelyekről Bonfini is megemlékezik. A pénzt a főrendek közt bátyja, Mihály osztotta szét, és ugyanő szedte össze a fegyveres erőt, amelynek meghatározó szerep volt szánva. Egyidejűleg Erzsébet Podiebrad György cseh kormányzónak 40.000 aranyat ígért Mátyás szabadon bocsátásáért. Ilyen előkészületek után érte el célját Mátyás megválasztásával, akinek hazafelé jöttében a magyar határon fekvő Strassnitz morva városig ment elébe s ott a maga pecsétjével is megerősítette azt az okiratot, amelyben Mátyás kötelezte magát Podiebrad leányának, Katalinnak nőül vételére. A boldog anyát a pápa is sietett üdvözölni.
Ettől fogva fiától és mindenkitől megbecsülve élt nyugodtan, birtokait igazgatva, többnyire Óbudán. Eredeti iratainak, rendeleteinek, utasítá- sainak egész halmazát őrzi az Országos Levéltár. Szeretettel foglalkozott Vajda-Hunyad, a XVI. sz.-ból fennmaradt, ezen legnagyobbszerű világi épületünk fölépítésével. A várpalota jelentékeny része abban az időben épült, amikor ő volt Hunyad várának birtokosa. Mint korának igazi gyermeke, nem mulasztotta el kegyes cselekedetekkel kimutatni vallásos érzületét. 1465-ben kolostort építtetett Vajda-Hunyadon a ferencesek számára, 1477-ben az óbudai várkápolnának adományozta Szente-Tornya (ma Szent-Tornya) békésvármegyei népes helységet. 1473. augusztus 8-án Óbudáról írt levelében arra kérte a pápát, hogy Kapisztrán Jánost, férjének lánglelkű és szent életű bajtársát sorolja a szentek közé.
<p>MEGBECSÜLTSÉGE</p>
Nagyon jellemző, hogy Mátyás udvarának tömérdek tudósa és poétája, akik versenyeztek a Beatrixnak, Mátyás király nejének magasz- talásában, a király anyjáról tudomást sem vesznek s Hunyadi János özvegye, Mátyás király anyja meghalhat úgy, hogy még halála évét sem jegyzik fel.Tatán halt meg valószínűleg 1483-ban a ferences kolostor ispotályában.(ez ma Tatán a Kapucinus-templom az Országgyűlés téren) Bonfini is csak annyit ír róla, hogy a székesfehérvári főtemplom azon bástyaszerű sírboltjába temették, amelyet Mátyás király a szülei, testvérei és a maga számára építtetett. Erzsébetet fia gyakran a “Magyarország királynéja” címmel tisztelte meg és sűrűn adományozott neki birtokokat, de amellett nemegyszer vette igénybe anyagi támogatását. Amikor 1470-ben nagy hadi költségre volt szüksége, tőle is megkívánta, hogy 100 dénárból álló arany forintot fizessen minden portája után.
<p>EMLÉKEZETE</p>
Szilágyi Erzsébet eredeti arcképe nem maradt reánk. Az az acélba metszett kép, amelyet Teleki József a Hunyadiak kora XII. kötetében az
ő arcképe gyanánt mutatott be, voltaképpen nem őt, hanem Szt. Ozsvátot ábrázolja. A remek olajkép - ugyanis - először 1846-ban került a közönség elé, az orvosok és természettudósok kassa-eperjesi vándorgyűlésén. Pulszky Ferenc ekkor, a képen ábrázolt, csőrében gyűrűt tartó hollótól, mint a Hunyadiak címerétől félrevezetve, a vándorgyűlés évkönyvében kijelentette, hogy ez a kép Szilágyi Erzsébetet ábrázolja. Mikor aztán 1882-ben, a gömörvármegyei művészeti és régészeti kiállításon ismét szemügyre vehette az Andrássy Dénes gróf által kiállított képet, rájött tévedésére, mert Mátyás anyját a korona és a jogar nem illette meg s a kettős aranyvonal, amely nimbusz (glória) gyanánt veszi körül a fejet, és a kezében tartott pálmaág kétségtelenné teszik, hogy szentnek, nem pedig világi személynek képével van dolgunk. Sőt az is nyilván- való, hogy ez nem is női-, hanem férfiarckép. A tévedésnek az a magyarázata, hogy a fekete fátyoldíszt, amely turbánként fedi el a haját s a XV. sz.-ban szokásos fűzőt asszonyi viseletnek nézték. Így történhetett meg, hogy Szt. Ozsvát angolszász király arcképét Pulszky s őutána Teleki József gróf és a mai napig számtalanan Mátyás király anyjáénak tartották.
<span>Szilágyi Erzsébetről írta Arany János Mátyás anyja című balladáját.</span>
			</div>

			<div class="school-history">
				<h3>ISKOLÁNK TÖRTÉNETE</h3>
<span>Lányok számára szervezett, az elemi oktatásnál magasabb szintű tanításról Magyarországon csak a XVIII. sz. második felétől tudunk. Budán az elsők között, 1881-ben alapították a Budapest fővárosi első kerületi nyilvános községi polgári leányiskolát, amely mai iskolánk elődje. Póra Ferenc alapította, az ő igazgatóságával kezdte meg működését a Várban. A régi épület a domonkosok kolostorának helyén állt, ahol ma a Hilton szálló található.</span>
<span>A polgári leányiskola három osztállyal, 147 tanulóval indult. Az iskola alapításának évében kezdte meg működését a budapesti telefonközpont, ekkor nyílt meg a Városligetben a fürdő, ebben az évben született Bartók Béla. Ekkor jelent meg Jókai Mór Akik kétszer halnak meg című regénye, Mikszáth Kálmán Tót atyafiak című elbeszéléskötete, ebben az évben festette Munkácsy Mihály Krisztus Pilátus előtt című képét. Ezek az adatok segítik elképzelni a főváros művelődését az 1800-as évek végén. Póra Ferenc kiváló nevelőket gyűjtött maga köré. Az iskola tekintélye évről-évre nőtt. Az intézmény az 1892-93-as tanévtől kezdve már 6 osztályú felsőbb leányiskola, az 1916-17-es tanévtől pedig leány- gimnázium. 1920-ban érettségizett az első osztály.</span>
<span>Az énekkar működése korai időkre nyúlik vissza. Sztojanovits Adrienne énektanárnő 1912-től tanított a gimnáziumban. Bartók Béla és Kodály Zoltán műveinek bemutatásával sok sikert ért el. 1929-ben Kodály Zoltán új darabját, a Pünkösdölőt, Sztojanovits Adriennenek és énekkarának ajánlotta.
A Szilágyi Erzsébet nevet iskolánk 1922-ben vette fel. Azóta hagyománnyá vált az Erzsébet-napi ünnepség, melyet a mai napig minden évben november 19-én megtartunk.
Jelenlegi épületünkben, a Mészáros utcában, 1936-ban kezdődött meg a tanítás. Az új helyen is tovább folytatódott a színvonalas oktató, nevelőmunka. 1938-tól kezdve azonban az európai események éreztetik negatív hatásukat. A második világháború sok veszteséget okoz.
1946-ban a gimnáziumot újjáépítették, korszerűsítették. Megindult a tanítás. Az énekkar szereplései újra előtérbe kerültek. Az Erzsébet-napi műsort a Zeneakadémián tartották meg. Az énekkar műsort adott a Rádióban, a Budai Vígadóban.</span>
<spane>Az 1948-as év az oktatási szerkezet átalakítását hozta, a Szilágyi Erzsébet Gimnázium ettől az évtől négyosztályos gimnáziumként működött. Az 1963-64-es tanévtől kezdve már fiúk is jártak az iskolába. Az idegen nyelvek színvonalas oktatását azokban az években is vállalta, amikor ezt a kor szelleme nem támogatta kiemelten. Tanulóink indultak az Országos Középiskolai Tanulmányi Versenyeken, sok első, második, harma- dik díjjal, további helyezésekkel öregbítve az iskola hírnevét.
1969-től iskolánk UNESCO asszociált iskola. Az UNESCO támogatásával sok diákcserében vettünk részt. A franciaországi Strasbourg és a németországi Heiligenhaus jelentette az első utazásokat. Mára már Európa számtalan országában jártak tanulóink. 1993 szeptemberétől iskolánk újra nyolcosztályos gimnáziumként működik.</spane>
			</div>
		</div>
		<?php include('footer.php'); ?>
	</body>
</html>